version: '3.8'

services:
  trading-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-trading-bot-professional
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    restart: unless-stopped
    networks:
      - ai-trading-network
    command: ["python", "-u", "app/main.py"]

networks:
  ai-trading-network:
    driver: bridge
    name: ai-trading-network