# AI/ML Trading Bot v3.0 - Professional Web GUI Configuration
# Configuration for trading strategies, risk management, and system settings

# Application Settings
app:
  name: "AI/ML Trading Bot v3.0"
  version: "3.0.0"
  description: "Professional Multi-Platform Trading System with Web GUI"
  debug: false
  port: 8000
  host: "0.0.0.0"

# Web GUI Settings
web_gui:
  enabled: true
  title: "AI/ML Trading Bot v3.0 - Professional Dashboard"
  auto_refresh_interval: 30  # seconds
  chart_default_period: "1M"
  theme: "professional"  # professional, dark, light
  responsive: true

# Risk Management (Fibonacci Team Standards)
risk_management:
  default_stop_loss_percent: 2.0  # 2% default stop loss
  max_risk_per_trade_percent: 1.5  # 1.5% of account per trade
  max_daily_trades: 10
  max_open_positions: 5
  risk_reward_ratio: 2.0  # Minimum 2:1 ratio
  max_drawdown_percent: 15.0
  position_sizing_method: "fixed_percent"  # fixed_percent, kelly, volatility

# Smart Money Concepts Strategy
smart_money_concepts:
  enabled: true
  swing_period: 10
  order_block_threshold: 0.002  # 0.2%
  fvg_threshold: 0.001  # 0.1% for Fair Value Gaps
  liquidity_threshold: 0.0015  # 0.15% for liquidity sweeps
  confluence_required: 3  # Minimum confluence factors

# Fibonacci Team Strategy  
fibonacci_team:
  enabled: true
  retracement_levels: [23.6, 38.2, 50.0, 61.8, 78.6]
  extension_levels: [61.8, 100.0, 161.8, 261.8]
  harmonic_patterns: ["Gartley", "Bat", "Butterfly", "Crab"]
  volume_analysis: true
  default_stop_loss: 2.0  # 2% as per Fibonacci Team methodology

# Machine Learning Settings
ml_settings:
  enabled: true
  models:
    randomforest:
      enabled: true
      n_estimators: 100
      max_depth: 10
      features: 47
      target_accuracy: 0.75
    lstm:
      enabled: true
      sequence_length: 60
      features: 20
      epochs: 50
      batch_size: 32
      target_accuracy: 0.70
    ensemble:
      enabled: true
      voting: "soft"  # soft, hard
      weights: [0.4, 0.35, 0.25]  # RF, LSTM, other
  
  online_learning:
    enabled: true
    retrain_threshold: 0.1  # Retrain when accuracy drops by 10%
    min_samples_retrain: 100
    max_memory_samples: 10000

# Multi-Platform Broker Support
brokers:
  mt5:
    enabled: false  # Set to true when real broker integration needed
    server: ""
    login: ""
    password: ""
    demo: true
  
  sabiotrade:
    enabled: false
    api_key: ""
    secret: ""
    demo: true
  
  # Add more brokers as needed
  supported_platforms:
    - "MT4/MT5"
    - "Sabiotrade" 
    - "RoboForex"
    - "XM Group"
    - "ForexChief"
    - "FXOpen"
    - "InstaForex"
    - "TemplerFX"
    - "FBS"
    - "Pocket Option"
    - "The5ers"
    - "Funded Trading Plus"

# Trading Instruments
instruments:
  forex_majors:
    - "EURUSD"
    - "GBPUSD" 
    - "USDJPY"
    - "AUDUSD"
    - "USDCAD"
    - "USDCHF"
    - "NZDUSD"
  
  forex_minors:
    - "EURGBP"
    - "EURJPY"
    - "GBPJPY"
    - "AUDJPY"
  
  crypto:
    - "BTCUSD"
    - "ETHUSD"
    - "BNBUSD"
  
  metals:
    - "XAUUSD"  # Gold
    - "XAGUSD"  # Silver

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "data/logs/trading_bot.log"
  max_file_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Data Settings
data:
  cache_enabled: true
  cache_duration: 3600  # seconds
  historical_data_source: "yahoo"  # yahoo, alpha_vantage, mt5
  real_time_data: false  # Set to true for live trading
  
# Security Settings
security:
  api_key_required: false  # Set to true for production
  rate_limiting: true
  max_requests_per_minute: 60
  encrypt_credentials: true

# Performance Settings
performance:
  max_concurrent_requests: 100
  request_timeout: 30  # seconds
  cache_size: 1000  # number of cached items
  enable_compression: true